"""
Back up lake/gold/nfl/*.csv to the private Hugging Face dataset
AIBRUH/big-proppa-lake -- redundancy for the data lake, not a second source of
truth (GitHub stays canonical). Re-run any time the lake changes.

Requires huggingface_hub and an authenticated HF session (HF_TOKEN env var, or
`huggingface-cli login` already run) -- never hardcode a token here.

Run from the repo root:
    pip install huggingface_hub
    python scripts/backup_lake_to_hf.py
"""
from __future__ import annotations

from pathlib import Path

from huggingface_hub import HfApi

REPO_ID = "AIBRUH/big-proppa-lake"
LAKE_DIR = Path(__file__).resolve().parent.parent / "lake" / "gold" / "nfl"

README = """---
license: other
---

# Big Proppa data lake (backup)

Private backup mirror of `lake/gold/nfl/` from
[tyronne-os/Hey-Big-Proppa](https://github.com/tyronne-os/Hey-Big-Proppa) on GitHub, which stays
the canonical source of truth -- this dataset is redundancy, not a second source.

Regenerated by, in order:
1. `scripts/build_team_game_stats.py` -- team-game stats from nflverse play-by-play (2023+)
2. `scripts/fit_matchup_model.py` -- fits and backtests the matchup predictor
3. `scripts/backtest_hot_dogs.py` -- the Hot Dog indicator's history + backtest

Re-uploaded by `scripts/backup_lake_to_hf.py` whenever the lake changes.
"""


def main() -> None:
    api = HfApi()
    api.create_repo(REPO_ID, repo_type="dataset", private=True, exist_ok=True)
    api.upload_folder(
        repo_id=REPO_ID, repo_type="dataset",
        folder_path=str(LAKE_DIR), path_in_repo="lake/gold/nfl",
        allow_patterns=["*.csv"],
    )
    api.upload_file(
        repo_id=REPO_ID, repo_type="dataset",
        path_or_fileobj=README.encode(), path_in_repo="README.md",
    )
    print(f"backed up {sum(1 for _ in LAKE_DIR.glob('*.csv'))} CSVs -> https://huggingface.co/datasets/{REPO_ID}")


if __name__ == "__main__":
    main()
